"use client";

import "../styles/globals.css";
import Providers from "@/app/providers";
import { DM_Sans } from "@next/font/google";
import QueryProvider from "../utils/queryProvider";
import React from "react";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { ThemeContextProvider } from "../contexts/lightDarkmode";
import { DndProvider } from "react-dnd";
import { HTML5Backend } from "react-dnd-html5-backend";

const dmSans = DM_Sans({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head />
      <body className={`${dmSans.className}`}>
        <ThemeContextProvider> 
          <Providers>
            <QueryProvider>
              <DndProvider backend={HTML5Backend}>
                <div className="bg-white dark:bg-gray-900 text-black dark:text-white min-h-screen">
                  {children}
                </div>
              </DndProvider>
            </QueryProvider>
          </Providers>
        </ThemeContextProvider>
        <ToastContainer />
      </body>
    </html>
  );
}